# Generated by Django 4.1.6 on 2023-02-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_rooms',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='service_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='property',
            name='service_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='type_of_building',
            field=models.CharField(choices=[('tenement', 'Kamienica'), ('block_of_flats', 'Blok'), ('apartment', 'Apartamentowiec')], default='block_of_flats', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('flat', 'Mieszkanie'), ('plot', 'Działka')], default='flat', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
