# Generated by Django 4.1.6 on 2023-03-25 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_scrape_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 17, 13, 0, 762282, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='modify_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 25, 17, 13, 0, 762296, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
