# Generated by Django 4.1.6 on 2023-03-25 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_create_date_property_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='modify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
