# Generated by Django 4.1.4 on 2023-04-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type_of_building',
            field=models.CharField(choices=[('tenement', 'Kamienica'), ('block_of_flats', 'Blok'), ('apartment', 'Apartamentowiec')], default=None, max_length=100, null=True),
        ),
    ]
