# Generated by Django 4.1.4 on 2023-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_type_of_plot'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default=None, max_length=255)),
                ('field_name', models.CharField(default=None, max_length=255)),
                ('value', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFilterIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default=None, max_length=255)),
                ('field_name', models.CharField(default=None, max_length=255)),
                ('service_id', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='building_floors_num',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='building_material',
            field=models.CharField(choices=[('brick', 'Cegła')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='construction_status',
            field=models.CharField(choices=[('to_completion', 'do wykończenia')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='district_neighbourhood',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electricity',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='fence',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='flat_ownership',
            field=models.CharField(choices=[('full_ownership', 'Pełna własność')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='forest_vicinity',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='formatted_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_heating',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_lighted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_localization',
            field=models.CharField(choices=[('in_building', 'w budynku'), ('separate', 'samodzielny')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='gas',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.CharField(choices=[('urban', 'Miejskie')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lake_vicinity',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='market_type',
            field=models.CharField(choices=[('primary', 'Pierwotny'), ('secondary', 'Wtórny')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='open_terrain_vicinity',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='regular_user',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='rent',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='service_url',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='sewerage',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type_of_flat',
            field=models.CharField(choices=[('tenement', 'Kamienica'), ('block_of_flats', 'Blok'), ('apartment', 'Apartamentowiec')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='type_of_offer',
            field=models.CharField(choices=[('sell', 'Sprzedaż'), ('rent', 'Wynajem')], default='sell', max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='water',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_of_construction',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_of_building',
            field=models.CharField(choices=[('agricultural', 'Rolna'), ('building', 'Budowlana'), ('recreational', 'Rekreacyjna'), ('forest', 'Leśna')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('flat', 'Mieszkanie'), ('plot', 'Działka'), ('house', 'Dom'), ('garage', 'Garaż')], default='flat', max_length=100),
        ),
    ]
