# Generated by Django 4.1.4 on 2023-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_missingvalues_servicefilterids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
