# Generated by Django 4.1.4 on 2023-05-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_construction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='basement',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_material',
            field=models.CharField(choices=[('brick', 'Cegła'), ('great_slab', 'Wielka płyta')], default=None, max_length=100, null=True),
        ),
    ]
