# Generated by Django 4.1.4 on 2023-05-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_basement_alter_property_building_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='year_of_construction',
            new_name='build_year',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type_of_building',
            new_name='house_type',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type_of_offer',
            new_name='offer_type',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type_of_plot',
            new_name='plot_type',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='type_of_property',
            new_name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='flat_ownership',
        ),
        migrations.AddField(
            model_name='property',
            name='ownership',
            field=models.CharField(choices=[('full_ownership', 'Pełna własność'), ('cooperative_ownership', 'Spółdzielcze własnościowe'), ('cooperative_tenant', 'Spółdzielcze lokatorskie'), ('government_housing', 'Komunalne')], default=None, max_length=100, null=True),
        ),
    ]
