# Generated by Django 4.1.4 on 2023-05-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_rename_year_of_construction_property_build_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type_of_flat',
            new_name='flat_type',
        ),
    ]
