# Generated by Django 4.1.4 on 2023-05-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_rename_type_of_flat_property_flat_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='formatted_address',
            new_name='address',
        ),
    ]
