# Generated by Django 4.1.4 on 2023-05-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_rename_formatted_address_property_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
