# Generated by Django 4.1.4 on 2023-05-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_property_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='radius',
            field=models.IntegerField(null=True),
        ),
    ]
