# Generated by Django 4.1.4 on 2023-06-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_property_radius'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='scrape_job_id',
            new_name='scrapyd_job_id',
        ),
    ]
